### ISSUE TITLE
Logging an exception directly produces a bad message

### ISSUE THREAD

**Issue by tremby** [twineis/raven-php#9]
When running `Log::error($exception)` with an Exception object (which is what the default error handler does, such as during an unhandled exception) an exception is logged to Sentry with a message like `Exception: test exception 2 in /home/vagrant/sparkit/routes/web.php:15 Stack trace: #0 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): App\Providers\RouteServiceProvider->{closure}() #1 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(147): Illuminate\Routing\Route->runCallable() #2 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #3 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #4 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #5 /home/vagrant/sparkit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindi`. Presumably this is a truncated form of `$exception->__toString()`.

Can the Monolog handler instead detect an Exception instance and deal with it properly?

This would allow exceptions to be logged directly, which both makes things easier for developers and allows the default Laravel exception handler to log exceptions to Sentry properly.

**Comment by pulkitjalan** [comment]
Yea this is an annoying issue. It was one i spent quite some time trying to resolve but i was unable to come up with a solution that did not involve replacing the in build laravel logger, and is even more problematic with lumen since that uses monolog directly. If you have any suggestions please let me know.

**Comment by pulkitjalan** [comment]
Some info on what causes the problem:

`Monolog\Logger@addRecord`

```php
$record = array(
    'message' => (string) $message,
    'context' => $context,
    'level' => $level,
    'level_name' => $levelName,
    'channel' => $this->name,
    'datetime' => $ts,
    'extra' => array(),
);
```

This is what monolog does to the message before it is sent to the handlers. So when the handlers get the message or the `Exception` it's already been converted into a string.

**Comment by tremby** [comment]
How did clowdy/raven solve this one?

**Comment by pulkitjalan** [comment]
It replaced the inbuilt logger addRecord function and added a check. If message was an exception then change message to $e->getMessage() and put the exception in the context then called parent::addRecord().

**Comment by tremby** [comment]
I see, and you don't want to do that again for the reasons you gave above. Tricky.

**Comment by pulkitjalan** [comment]
No not necessarily, as i think this would be the only solution, i would like to replace the monolog logger binding instead of replacing the Laravel logger. Laravel has a separate [logger class](https://github.com/laravel/framework/blob/master/src/Illuminate/Log/Writer.php) however Lumen directly uses monolog's logger class. For it to work on both I think it would be best to overwrite the monolog logger class binding with a custom one, which extends monolog's logger class, and does what i have mentioned in my above comments.

**Comment by pulkitjalan** [comment]
I've made the changes on the develop branch. Try it out.

**Comment by tremby** [comment]
This works for me on Laravel. Thanks. I thought it caused an issue with user data (from my monolog processor), and spent a while debugging only to find that it's actually an updated version of sentry-php (1.6.0) which caused this.
